global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus.newbury.inthearea.party']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor.newbury.inthearea.party']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter.newbury.inthearea.party']

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager.newbury.inthearea.party']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://grafana.newbury.inthearea.party
          - https://prometheus.newbury.inthearea.party
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115


alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager.newbury.inthearea.party