services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.8.7
    container_name: homepage
    restart: unless-stopped

    ports:
      - "10355:3000"

    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro

    environment:
      - TZ=Europe/London
      - HOMEPAGE_ALLOWED_HOSTS=*
    networks:
      - monitoring


networks:
  monitoring:
    external: true
    name: monitoring_monitoring